defaults: &defaults
  adapter: mysql

development:
  database: emporiumsj
  username: dkamioka
  password: aixdw
  host: box.strikeout.com.br
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: db/emporiumsj-reports_test.db
  <<: *defaults
#production:
#  database: db/emporiumsj-reports_production.db
#  <<: *defaults
